//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreClient.DeveloperService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppCategoryDataContract", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract")]
    [System.SerializableAttribute()]
    public partial class AppCategoryDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreClient.DeveloperService.AppType AppTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreClient.DeveloperService.AppType AppType {
            get {
                return this.AppTypeField;
            }
            set {
                if ((this.AppTypeField.Equals(value) != true)) {
                    this.AppTypeField = value;
                    this.RaisePropertyChanged("AppType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppType", Namespace="http://schemas.datacontract.org/2004/07/Store.Common.Enum")]
    public enum AppType : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Application = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Game = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppDataContract", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract")]
    [System.SerializableAttribute()]
    public partial class AppDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreClient.DeveloperService.AppCategoryDataContract AppCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] IconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreClient.DeveloperService.AppCategoryDataContract AppCategory {
            get {
                return this.AppCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.AppCategoryField, value) != true)) {
                    this.AppCategoryField = value;
                    this.RaisePropertyChanged("AppCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Icon {
            get {
                return this.IconField;
            }
            set {
                if ((object.ReferenceEquals(this.IconField, value) != true)) {
                    this.IconField = value;
                    this.RaisePropertyChanged("Icon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Name {
            get {
                return this.NameField;
            }
            set {
                if ((this.NameField.Equals(value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDataContract", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StoreClient.DeveloperService.LegalPersonDataContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StoreClient.DeveloperService.NaturalPersonDataContract))]
    public partial class PersonDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNaturalPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreClient.DeveloperService.LegalPersonDataContract LegalPersonDataContractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreClient.DeveloperService.NaturalPersonDataContract NaturalPersonDataContractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNaturalPerson {
            get {
                return this.IsNaturalPersonField;
            }
            set {
                if ((this.IsNaturalPersonField.Equals(value) != true)) {
                    this.IsNaturalPersonField = value;
                    this.RaisePropertyChanged("IsNaturalPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreClient.DeveloperService.LegalPersonDataContract LegalPersonDataContract {
            get {
                return this.LegalPersonDataContractField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalPersonDataContractField, value) != true)) {
                    this.LegalPersonDataContractField = value;
                    this.RaisePropertyChanged("LegalPersonDataContract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreClient.DeveloperService.NaturalPersonDataContract NaturalPersonDataContract {
            get {
                return this.NaturalPersonDataContractField;
            }
            set {
                if ((object.ReferenceEquals(this.NaturalPersonDataContractField, value) != true)) {
                    this.NaturalPersonDataContractField = value;
                    this.RaisePropertyChanged("NaturalPersonDataContract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryEmail {
            get {
                return this.PrimaryEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryEmailField, value) != true)) {
                    this.PrimaryEmailField = value;
                    this.RaisePropertyChanged("PrimaryEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LegalPersonDataContract", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract")]
    [System.SerializableAttribute()]
    public partial class LegalPersonDataContract : StoreClient.DeveloperService.PersonDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NaturalPersonDataContract", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract")]
    [System.SerializableAttribute()]
    public partial class NaturalPersonDataContract : StoreClient.DeveloperService.PersonDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreClient.DeveloperService.Sexuality SexualityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode {
            get {
                return this.NationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalCodeField, value) != true)) {
                    this.NationalCodeField = value;
                    this.RaisePropertyChanged("NationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreClient.DeveloperService.Sexuality Sexuality {
            get {
                return this.SexualityField;
            }
            set {
                if ((this.SexualityField.Equals(value) != true)) {
                    this.SexualityField = value;
                    this.RaisePropertyChanged("Sexuality");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sexuality", Namespace="http://schemas.datacontract.org/2004/07/Store.Common.Enum")]
    public enum Sexuality : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResultDataContract", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResultDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreClient.DeveloperService.UserAccountStatus UserAccountStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreClient.DeveloperService.IdentificationInformationDataContract UserIdentityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Authenticated {
            get {
                return this.AuthenticatedField;
            }
            set {
                if ((this.AuthenticatedField.Equals(value) != true)) {
                    this.AuthenticatedField = value;
                    this.RaisePropertyChanged("Authenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreClient.DeveloperService.UserAccountStatus UserAccountStatus {
            get {
                return this.UserAccountStatusField;
            }
            set {
                if ((this.UserAccountStatusField.Equals(value) != true)) {
                    this.UserAccountStatusField = value;
                    this.RaisePropertyChanged("UserAccountStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreClient.DeveloperService.IdentificationInformationDataContract UserIdentity {
            get {
                return this.UserIdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdentityField, value) != true)) {
                    this.UserIdentityField = value;
                    this.RaisePropertyChanged("UserIdentity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentificationInformationDataContract", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract")]
    [System.SerializableAttribute()]
    public partial class IdentificationInformationDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNaturalPersonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNaturalPerson {
            get {
                return this.IsNaturalPersonField;
            }
            set {
                if ((this.IsNaturalPersonField.Equals(value) != true)) {
                    this.IsNaturalPersonField = value;
                    this.RaisePropertyChanged("IsNaturalPerson");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccountStatus", Namespace="http://schemas.datacontract.org/2004/07/Store.Common.Enum")]
    public enum UserAccountStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activated = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotActivated = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralInternalFault", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract.SoapFaults")]
    [System.SerializableAttribute()]
    public partial class GeneralInternalFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreClient.DeveloperService.FaultCode FaultCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreClient.DeveloperService.FaultCode FaultCode {
            get {
                return this.FaultCodeField;
            }
            set {
                if ((this.FaultCodeField.Equals(value) != true)) {
                    this.FaultCodeField = value;
                    this.RaisePropertyChanged("FaultCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultCode", Namespace="http://schemas.datacontract.org/2004/07/Store.Common.Enum")]
    public enum FaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVerificationCode = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingParameters", Namespace="http://schemas.datacontract.org/2004/07/Store.Common.Infrastructure")]
    [System.SerializableAttribute()]
    public partial class PagingParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationFault", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract.SoapFaults")]
    [System.SerializableAttribute()]
    public partial class AuthenticationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Paasteel.com", ConfigurationName="DeveloperService.IDeveloperService")]
    public interface IDeveloperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/GetAppCategories", ReplyAction="Paasteel.com/IDeveloperService/GetAppCategoriesResponse")]
        StoreClient.DeveloperService.AppCategoryDataContract[] GetAppCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/GetAppCategories", ReplyAction="Paasteel.com/IDeveloperService/GetAppCategoriesResponse")]
        System.Threading.Tasks.Task<StoreClient.DeveloperService.AppCategoryDataContract[]> GetAppCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/RegisterApp", ReplyAction="Paasteel.com/IDeveloperService/RegisterAppResponse")]
        void RegisterApp(StoreClient.DeveloperService.AppDataContract appDataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/RegisterApp", ReplyAction="Paasteel.com/IDeveloperService/RegisterAppResponse")]
        System.Threading.Tasks.Task RegisterAppAsync(StoreClient.DeveloperService.AppDataContract appDataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/RegisterNaturalPerson", ReplyAction="Paasteel.com/IDeveloperService/RegisterNaturalPersonResponse")]
        void RegisterNaturalPerson(StoreClient.DeveloperService.NaturalPersonDataContract dataContract, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/RegisterNaturalPerson", ReplyAction="Paasteel.com/IDeveloperService/RegisterNaturalPersonResponse")]
        System.Threading.Tasks.Task RegisterNaturalPersonAsync(StoreClient.DeveloperService.NaturalPersonDataContract dataContract, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/SignIn", ReplyAction="Paasteel.com/IDeveloperService/SignInResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StoreClient.DeveloperService.GeneralInternalFault), Action="Paasteel.com/IDeveloperService/SignInGeneralInternalFaultFault", Name="GeneralInternalFault", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract.SoapFaults")]
        StoreClient.DeveloperService.AuthenticationResultDataContract SignIn(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/SignIn", ReplyAction="Paasteel.com/IDeveloperService/SignInResponse")]
        System.Threading.Tasks.Task<StoreClient.DeveloperService.AuthenticationResultDataContract> SignInAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/IsEmailAvailableForRegistration", ReplyAction="Paasteel.com/IDeveloperService/IsEmailAvailableForRegistrationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StoreClient.DeveloperService.GeneralInternalFault), Action="Paasteel.com/IDeveloperService/IsEmailAvailableForRegistrationGeneralInternalFaul" +
            "tFault", Name="GeneralInternalFault", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract.SoapFaults")]
        bool IsEmailAvailableForRegistration(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/IsEmailAvailableForRegistration", ReplyAction="Paasteel.com/IDeveloperService/IsEmailAvailableForRegistrationResponse")]
        System.Threading.Tasks.Task<bool> IsEmailAvailableForRegistrationAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/TryActivateAccount", ReplyAction="Paasteel.com/IDeveloperService/TryActivateAccountResponse")]
        bool TryActivateAccount(string primaryEmail, string activationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/TryActivateAccount", ReplyAction="Paasteel.com/IDeveloperService/TryActivateAccountResponse")]
        System.Threading.Tasks.Task<bool> TryActivateAccountAsync(string primaryEmail, string activationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/ResendActivationCode", ReplyAction="Paasteel.com/IDeveloperService/ResendActivationCodeResponse")]
        void ResendActivationCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/ResendActivationCode", ReplyAction="Paasteel.com/IDeveloperService/ResendActivationCodeResponse")]
        System.Threading.Tasks.Task ResendActivationCodeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/GetDeveloperApps", ReplyAction="Paasteel.com/IDeveloperService/GetDeveloperAppsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StoreClient.DeveloperService.AuthenticationFault), Action="Paasteel.com/IDeveloperService/GetDeveloperAppsAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.datacontract.org/2004/07/Store.DataContract.SoapFaults")]
        StoreClient.DeveloperService.AppDataContract[] GetDeveloperApps(StoreClient.DeveloperService.PagingParameters pagingParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="Paasteel.com/IDeveloperService/GetDeveloperApps", ReplyAction="Paasteel.com/IDeveloperService/GetDeveloperAppsResponse")]
        System.Threading.Tasks.Task<StoreClient.DeveloperService.AppDataContract[]> GetDeveloperAppsAsync(StoreClient.DeveloperService.PagingParameters pagingParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeveloperServiceChannel : StoreClient.DeveloperService.IDeveloperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeveloperServiceClient : System.ServiceModel.ClientBase<StoreClient.DeveloperService.IDeveloperService>, StoreClient.DeveloperService.IDeveloperService {
        
        public DeveloperServiceClient() {
        }
        
        public DeveloperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeveloperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeveloperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeveloperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StoreClient.DeveloperService.AppCategoryDataContract[] GetAppCategories() {
            return base.Channel.GetAppCategories();
        }
        
        public System.Threading.Tasks.Task<StoreClient.DeveloperService.AppCategoryDataContract[]> GetAppCategoriesAsync() {
            return base.Channel.GetAppCategoriesAsync();
        }
        
        public void RegisterApp(StoreClient.DeveloperService.AppDataContract appDataContract) {
            base.Channel.RegisterApp(appDataContract);
        }
        
        public System.Threading.Tasks.Task RegisterAppAsync(StoreClient.DeveloperService.AppDataContract appDataContract) {
            return base.Channel.RegisterAppAsync(appDataContract);
        }
        
        public void RegisterNaturalPerson(StoreClient.DeveloperService.NaturalPersonDataContract dataContract, string password) {
            base.Channel.RegisterNaturalPerson(dataContract, password);
        }
        
        public System.Threading.Tasks.Task RegisterNaturalPersonAsync(StoreClient.DeveloperService.NaturalPersonDataContract dataContract, string password) {
            return base.Channel.RegisterNaturalPersonAsync(dataContract, password);
        }
        
        public StoreClient.DeveloperService.AuthenticationResultDataContract SignIn(string userName, string password) {
            return base.Channel.SignIn(userName, password);
        }
        
        public System.Threading.Tasks.Task<StoreClient.DeveloperService.AuthenticationResultDataContract> SignInAsync(string userName, string password) {
            return base.Channel.SignInAsync(userName, password);
        }
        
        public bool IsEmailAvailableForRegistration(string email) {
            return base.Channel.IsEmailAvailableForRegistration(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmailAvailableForRegistrationAsync(string email) {
            return base.Channel.IsEmailAvailableForRegistrationAsync(email);
        }
        
        public bool TryActivateAccount(string primaryEmail, string activationCode) {
            return base.Channel.TryActivateAccount(primaryEmail, activationCode);
        }
        
        public System.Threading.Tasks.Task<bool> TryActivateAccountAsync(string primaryEmail, string activationCode) {
            return base.Channel.TryActivateAccountAsync(primaryEmail, activationCode);
        }
        
        public void ResendActivationCode(string email) {
            base.Channel.ResendActivationCode(email);
        }
        
        public System.Threading.Tasks.Task ResendActivationCodeAsync(string email) {
            return base.Channel.ResendActivationCodeAsync(email);
        }
        
        public StoreClient.DeveloperService.AppDataContract[] GetDeveloperApps(StoreClient.DeveloperService.PagingParameters pagingParameters) {
            return base.Channel.GetDeveloperApps(pagingParameters);
        }
        
        public System.Threading.Tasks.Task<StoreClient.DeveloperService.AppDataContract[]> GetDeveloperAppsAsync(StoreClient.DeveloperService.PagingParameters pagingParameters) {
            return base.Channel.GetDeveloperAppsAsync(pagingParameters);
        }
    }
}
